routes/web.php
<?php

Route::get('/', 'PageController@index')->name('home');

Route::resource('cuisines', 'CuisineController')->only(['index', 'show']);
Route::resource('categories', 'CategoryController')->only(['index', 'show']);
Route::resource('dishes', 'DishController')->only(['index', 'show']);


// Cart
Route::group(['prefix' => 'cart',/* 'middleware' => 'auth',*/ 'as' => 'cart.'], function () {
    Route::get('/', 'CartController@index')->name('index');
    Route::get('{dish}/increase', 'CartController@increaseItem')->name('increase');
    Route::get('{dish}/decrease', 'CartController@decreaseItem')->name('decrease');
    Route::get('{dish}/remove', 'CartController@removeItem')->name('remove');
    Route::get('clear', 'CartController@clearCart')->name('clear');
});


// Order
Route::resource('order', 'OrderController')
    ->middleware('auth')
    ->only(['store', 'show']);


// User Panel
Route::group(['prefix' => 'user', 'middleware' => 'auth', 'as' => 'user.'], function () {
    Route::get('/', 'UserController@userIndex')->name('index');
    Route::get('edit', 'UserController@userEdit')->name('edit');
    Route::post('edit/profile', 'UserController@userUpdateProfile')
        ->name('update.profile');
    Route::post('edit/password', 'UserController@userUpdatePassword')
        ->name('update.password');
//    Route::match(['get', 'post'], 'delete', 'UserController@userDestroy')
//        ->name('delete');
});


// Admin Panel
Route::group([
    'prefix' => 'admin',
    'middleware' => ['auth', 'admin'],
    'as' => 'admin.',
], function () {
    Route::get('/', 'AdminController@index')->name('index');

    Route::get('users', 'UserController@admin')->name('users.index');
    Route::get('users/{user}/delete', 'UserController@destroy')
        ->name('users.delete');
    Route::resource('users', 'UserController',
        ['except' => ['index', 'show']]
    );

    Route::get('pages', 'PageController@admin')->name('pages.index');
    Route::get('pages/{page}/delete', 'PageController@destroy')
        ->name('pages.delete');
    Route::resource('pages', 'PageController',
        ['except' => ['index', 'show']]
    );

    Route::get('cuisines', 'CuisineController@admin')
        ->name('cuisines.index');
    Route::get('cuisines/{cuisine}/delete', 'CuisineController@destroy')
        ->name('cuisines.delete');
    Route::resource('cuisines', 'CuisineController',
        ['except' => ['index', 'show']]
    );

    Route::get('categories', 'CategoryController@admin')->name('categories.index');
    Route::get('categories/{category}/delete', 'CategoryController@destroy')
        ->name('categories.delete');
    Route::resource('categories', 'CategoryController',
        ['except' => ['index', 'show']]
    );

    Route::get('dishes', 'DishController@admin')->name('dishes.index');
    Route::get('dishes/{dish}/delete', 'DishController@destroy')
        ->name('dishes.delete');
    Route::resource('dishes', 'DishController',
        ['except' => ['index', 'show']]
    );

    Route::get('cooks', 'CookController@admin')->name('cooks.index');
    Route::get('cooks/{cook}/delete', 'CookController@destroy')
        ->name('cooks.delete');
    Route::resource('cooks', 'CookController',
        ['except' => ['index', 'show']]
    );

    Route::get('orders', 'OrderController@admin')->name('orders.index');
    Route::resource('orders', 'OrderController',
        ['only' => ['edit', 'update']]
    );

    Route::group(['prefix' => '{nav}-nav', 'as' => 'nav.'], function () {
        Route::get('/', 'NavController@admin')->name('index');
        Route::post('/', 'NavController@store')->name('store');
        Route::get('move/{link}/{direction}', 'NavController@move')->name('move');
        Route::get('delete/{link}', 'NavController@destroy')->name('delete');
        Route::get('edit', 'NavController@navEdit')->name('edit');
        Route::post('edit', 'NavController@navUpdate')->name('update');
    });
});


Auth::routes();


// Other page
Route::get('{alias}', 'PageController@show');

app/Cart.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cart extends Model
{

    // Определяем стандартные свойства
    public $items = null; // продукты
    public $totalQty = 0; // общее колличество товаров
    public $totalPrice = 0; // общая цена

    // Создаем объект с данными корзины
    public function __construct()
    {
        // Извлекаем корзину из сессии
        $oldCart = session('cart', null);

        if ($oldCart) {
            // заменяем дефолтные значения
            $this->items = $oldCart->items;

            // заменяем дефолтные значения
            $this->totalQty = $oldCart->totalQty;

            // заменяем дефолтные значения
            $this->totalPrice = $oldCart->totalPrice;
        }
    }


    // Добавляем продукт или увеличиваем количество
    public function increase($product)
    {
        // Если корзина не пустая и в ней есть переданный продукт
        if ($this->items && array_key_exists($product->id, $this->items)) {
            // извлекаем продукт
            $cartItem = $this->items[$product->id];

            // увеличиваем его количество
            $cartItem['qty']++;

            // и вычисляем сумму
            $cartItem['price'] = $product->price * $cartItem['qty'];
        } else {
            // иначе создаем массив с данными продукта
            $cartItem = [
                'qty'   => 1, // количество
                'price' => $product->price, // сумма
                'item'  => $product // продукт
            ];
        }

        // Сохраняем продукт
        $this->items[$product->id] = $cartItem;

        // Увеличеваем общее количество товаров
        $this->totalQty++;

        // Увеличеваем общую сумму
        $this->totalPrice += $product->price;
    }


    // Уменьшаем количество или удаляем
    public function decrease($product)
    {
        // Если корзина не пустая и в ней есть переданный продукт
        if ($this->items && array_key_exists($product->id, $this->items)) {
            // извлекаем продукт
            $cartItem = $this->items[$product->id];

            // уменьшаем его количество
            $cartItem['qty']--;

            // если количество равно нулю, удаляем продукт
            if (!$cartItem['qty']) {
                unset($this->items[$product->id]);
            } else {
                // иначе вычисляем сумму
                $cartItem['price'] = $product->price * $cartItem['qty'];

                // и сохраняем
                $this->items[$product->id] = $cartItem;
            }

            // Уменьшаем общее количество товаров
            $this->totalQty--;

            // если общее количество равно нулю, удаляем корзину
            if (!$this->totalQty) {
                self::clear();
            } else {
                // Уменьшаем общую сумму
                $this->totalPrice -= $product->price;
            }
        }
    }


    // Удаляем пункт
    public function remove($product)
    {
        // Если корзина не пустая и в ней есть переданный продукт
        if ($this->items && array_key_exists($product->id, $this->items)) {
            // извлекаем продукт
            $cartItem = $this->items[$product->id];

            // удаляем продукт
            unset($this->items[$product->id]);

            // Уменьшаем общее количество товаров
            $this->totalQty -= $cartItem['qty'];

            // если общее количество равно нулю, удаляем корзину
            if (!$this->totalQty) {
                self::clear();
            } else {
                // иначе уменьшаем общую сумму
                $this->totalPrice -= $cartItem['price'];
            }
        }
    }


    // Удаляем корзину из сессии
    public static function clear()
    {
        session()->forget('cart');
    }

}

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use App\Cart;
use Illuminate\Http\Request;
use Auth;
use App\Dish;

class CartController extends Controller
{

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('site.cart.index');
    }

    public function ajaxIndex()
    {
        return view('site.cart.ajaxIndex');
    }

    public function apiIndex()
    {
        $cart = new Cart();
        $data = [
            'cart' => [
                'items' => $cart->items,
                'total_qty' => $cart->totalQty,
                'total_price' => $cart->totalPrice
            ]
        ];
        return session()->has('cart') ? $data : null;
    }


    /**
     * @param \App\Dish $dish
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function increaseItem(Dish $dish)
    {
        // Создаем объект с данными корзины
        $cart = new Cart();

        // Добавляем продукт в корзину
        $cart->increase($dish);

        // Записываем корзину в сессию
        session(['cart' => $cart]);

        return redirect()->back();
    }

    public function apiIncreaseItem($id)
    {
        $dish = Dish::find($id);
        $cart = new Cart();
        $cart->increase($dish);
        session(['cart' => $cart]);
        $data = [
            'cart' => [
                'items' => $cart->items,
                'total_qty' => $cart->totalQty,
                'total_price' => $cart->totalPrice
            ]
        ];
        return $data;
    }


    /**
     * @param \App\Dish $dish
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function decreaseItem(Dish $dish)
    {
        // Создаем объект с данными корзины
        $cart = new Cart();

        // Уменьшаем количество
        $cart->decrease($dish);

        // Если корзина не пустая
        if (session()->has('cart')) {
            // Записываем корзину в сессию
            session(['cart' => $cart]);
        }

        return redirect()->back();
    }

    public function apiDecreaseItem($id)
    {
        $dish = Dish::find($id);
        $cart = new Cart();
        $cart->decrease($dish);
        if (session()->has('cart')) {
            session(['cart' => $cart]);

            $data = [
                'cart' => [
                    'items' => $cart->items,
                    'total_qty' => $cart->totalQty,
                    'total_price' => $cart->totalPrice
                ]
            ];
            return $data;
        }

        return null;
    }


    /**
     * @param \App\Dish $dish
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function removeItem(Dish $dish)
    {
        // Создаем объект с данными корзины
        $cart = new Cart();

        // Удаляем пункт
        $cart->remove($dish);

        // Если корзина не пустая
        if (session()->has('cart')) {
            // Записываем корзину в сессию
            session(['cart' => $cart]);
        }

        return redirect()->back();
    }

    public function apiRemoveItem($id)
    {
        $dish = Dish::find($id);
        $cart = new Cart();
        $cart->remove($dish);
        if (session()->has('cart')) {
            session(['cart' => $cart]);

            $data = [
                'cart' => [
                    'items' => $cart->items,
                    'total_qty' => $cart->totalQty,
                    'total_price' => $cart->totalPrice
                ]
            ];
            return $data;
        }

        return null;
    }


    /**
     * Чистим корзину
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function clearCart()
    {
        Cart::clear();

        return redirect()->back();
    }

    public function apiClearCart()
    {
        Cart::clear();

        return $this->apiIndex();
    }
}

resources/views/site/cart/ajaxIndex.blade.php
<section class="cart">
    <div class="wrapper">
        @if(session('cart'))
            <table>
                <tr>
                    <th>№</th>
                    <th>Блюдо</th>
                    <th>Цена</th>
                    <th>Кол-во</th>
                    <th>Сумма</th>
                </tr>
                @foreach(session('cart')->items as $dish)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $dish['item']->title }}</td>
                        <td>{{ $dish['item']->price }}</td>
                        <td class="qty"><a href="">-</a>{{ $dish['qty'] }}<a href="">+</a></td>
                        <td>{{ $dish['price'] }}</td>
                    </tr>
                @endforeach
                <tr class="total">
                    <td colspan="3">Итого:</td>
                    <td>{{ session('cart')->totalQty }}</td>
                    <td>{{ session('cart')->totalPrice }}</td>
                </tr>
            </table>
        @else
            <p>Корзина пуста.</p>
        @endif
    </div>
</section>

resources/views/site/cart/index.blade.php
@extends('layouts.site')

@section('pageDescription', '')
@section('pageTitle', 'Корзина | ')

@section('content')
    <section class="cart">
        <div class="wrapper">
            <cart></cart>
            {{--@if(session('cart'))--}}
                {{--<table>--}}
                {{--<tr>--}}
                {{--<th>№</th>--}}
                {{--<th>Блюдо</th>--}}
                {{--<th>Цена</th>--}}
                {{--<th>Кол-во</th>--}}
                {{--<th>Сумма</th>--}}
                {{--<th>Удалить</th>--}}
                {{--</tr>--}}
                {{--@foreach(session('cart')->items as $dish)--}}
                {{--<tr>--}}
                {{--<td>{{ $loop->iteration }}</td>--}}
                {{--<td>{{ $dish['item']->title }}</td>--}}
                {{--<td>{{ $dish['item']->price }} руб.</td>--}}
                {{--<td>--}}
                {{--<div class="qty">--}}
                {{--<a href="{{ route('cart.decrease', $dish['item']) }}">-</a>--}}
                {{--<span>{{ $dish['qty'] }}</span>--}}
                {{--<a href="{{ route('cart.increase', $dish['item']) }}">+</a>--}}
                {{--</div>--}}
                {{--</td>--}}
                {{--<td>{{ $dish['price'] }} руб.</td>--}}
                {{--<td>--}}
                {{--<div class="delete">--}}
                {{--<a href="{{ route('cart.remove', $dish['item']) }}">--}}
                {{--<i class="fa fa-trash" aria-hidden="true"></i>--}}
                {{--</a>--}}
                {{--</div>--}}
                {{--</td>--}}
                {{--</tr>--}}
                {{--@endforeach--}}
                {{--<tr class="total">--}}
                {{--<td colspan="3">Итого:</td>--}}
                {{--<td>{{ session('cart')->totalQty }}</td>--}}
                {{--<td colspan="2">{{ session('cart')->totalPrice }} руб.</td>--}}
                {{--</tr>--}}
                {{--</table>--}}

                {{--<div class="manage">--}}
                    {{--{{ link_to_route('cart.clear', 'Очистить корзину', null, ['class' => 'clear']) }}--}}
                    {{--{{ link_to_route('order.store', 'Оформить заказ', null,--}}
                    {{--['class' => 'order', 'onclick' => 'event.preventDefault(); document.getElementById("order-store").submit();']) }}--}}
                    {{--{!! Form::open(['route'=>'order.store', 'id'=>'order-store', 'style'=>'display:none']) !!}--}}
                    {{--{!! Form::close() !!}--}}
                {{--</div>--}}
            {{--@else--}}
                {{--<p>В вашей корзине нет товаров</p>--}}
            {{--@endif--}}
        </div>
    </section>
@endsection