routes/web.php
<?php

Route::get('/', 'PageController@index')->name('home');

Route::resource('cuisines', 'CuisineController')->only(['index', 'show']);
Route::resource('categories', 'CategoryController')->only(['index', 'show']);
Route::resource('dishes', 'DishController')->only(['index', 'show']);


// Cart
Route::group(['prefix' => 'cart',/* 'middleware' => 'auth',*/ 'as' => 'cart.'], function () {
    Route::get('/', 'CartController@index')->name('index');
    Route::get('{dish}/increase', 'CartController@increaseItem')->name('increase');
    Route::get('{dish}/decrease', 'CartController@decreaseItem')->name('decrease');
    Route::get('{dish}/remove', 'CartController@removeItem')->name('remove');
    Route::get('clear', 'CartController@clearCart')->name('clear');
});


// Order
Route::resource('order', 'OrderController')
    ->middleware('auth')
    ->only(['store', 'show']);


// User Panel
Route::group(['prefix' => 'user', 'middleware' => 'auth', 'as' => 'user.'], function () {
    Route::get('/', 'UserController@userIndex')->name('index');
    Route::get('edit', 'UserController@userEdit')->name('edit');
    Route::post('edit/profile', 'UserController@userUpdateProfile')
        ->name('update.profile');
    Route::post('edit/password', 'UserController@userUpdatePassword')
        ->name('update.password');
//    Route::match(['get', 'post'], 'delete', 'UserController@userDestroy')
//        ->name('delete');
});


// Admin Panel
Route::group([
    'prefix' => 'admin',
    'middleware' => ['auth', 'admin'],
    'as' => 'admin.',
], function () {
    Route::get('/', 'AdminController@index')->name('index');

    Route::get('users', 'UserController@admin')->name('users.index');
    Route::get('users/{user}/delete', 'UserController@destroy')
        ->name('users.delete');
    Route::resource('users', 'UserController',
        ['except' => ['index', 'show']]
    );

    Route::get('pages', 'PageController@admin')->name('pages.index');
    Route::get('pages/{page}/delete', 'PageController@destroy')
        ->name('pages.delete');
    Route::resource('pages', 'PageController',
        ['except' => ['index', 'show']]
    );

    Route::get('cuisines', 'CuisineController@admin')
        ->name('cuisines.index');
    Route::get('cuisines/{cuisine}/delete', 'CuisineController@destroy')
        ->name('cuisines.delete');
    Route::resource('cuisines', 'CuisineController',
        ['except' => ['index', 'show']]
    );

    Route::get('categories', 'CategoryController@admin')->name('categories.index');
    Route::get('categories/{category}/delete', 'CategoryController@destroy')
        ->name('categories.delete');
    Route::resource('categories', 'CategoryController',
        ['except' => ['index', 'show']]
    );

    Route::get('dishes', 'DishController@admin')->name('dishes.index');
    Route::get('dishes/{dish}/delete', 'DishController@destroy')
        ->name('dishes.delete');
    Route::resource('dishes', 'DishController',
        ['except' => ['index', 'show']]
    );

    Route::get('cooks', 'CookController@admin')->name('cooks.index');
    Route::get('cooks/{cook}/delete', 'CookController@destroy')
        ->name('cooks.delete');
    Route::resource('cooks', 'CookController',
        ['except' => ['index', 'show']]
    );

    Route::get('orders', 'OrderController@admin')->name('orders.index');
    Route::resource('orders', 'OrderController',
        ['only' => ['edit', 'update']]
    );

    Route::group(['prefix' => '{nav}-nav', 'as' => 'nav.'], function () {
        Route::get('/', 'NavController@admin')->name('index');
        Route::post('/', 'NavController@store')->name('store');
        Route::get('move/{link}/{direction}', 'NavController@move')->name('move');
        Route::get('delete/{link}', 'NavController@destroy')->name('delete');
        Route::get('edit', 'NavController@navEdit')->name('edit');
        Route::post('edit', 'NavController@navUpdate')->name('update');
    });
});


Auth::routes();


// Other page
Route::get('{alias}', 'PageController@show');

resources/views/admin/index.blade.php
@extends('layouts.admin')

@section('pageDescription', '')
@section('pageTitle', 'Админпанель | ')

@section('breadcrumb', Breadcrumbs::render(Route::currentRouteName()))

@section('content')
    <div class="info-items">
        <div class="info-item">
            <a href="{{ route('admin.users.index') }}">
                <div class="title">Пользователи</div>
                <div class="info">{{ $users->count() }}</div>
            </a>
        </div>
        <div class="info-item">
            <a href="{{ route('admin.pages.index') }}">
                <div class="title">Страницы</div>
                <div class="info">{{ $pages->count() }}</div>
            </a>
        </div>
        <div class="info-item">
            <a href="{{ route('admin.cuisines.index') }}">
                <div class="title">Кухни</div>
                <div class="info">{{ $cuisines->count() }}</div>
            </a>
        </div>
        <div class="info-item">
            <a href="{{ route('admin.categories.index') }}">
                <div class="title">Категории</div>
                <div class="info">{{ $categories->count() }}</div>
            </a>
        </div>
        <div class="info-item">
            <a href="{{ route('admin.dishes.index') }}">
                <div class="title">Блюда</div>
                <div class="info">{{ $dishes->count() }}</div>
            </a>
        </div>
        <div class="info-item">
            <a href="{{ route('admin.cooks.index') }}">
                <div class="title">Повара</div>
                <div class="info">{{ $cooks->count() }}</div>
            </a>
        </div>
        <div class="info-item">
            <a href="{{ route('admin.orders.index') }}">
                <div class="title">Заказы</div>
                <div class="info">
                    <span class="active">{{ $orders->where('status',1)->count() }}</span>
                    <span>/</span>
                    <span class="inactive">{{ $orders->where('status',0)->count() }}</span>
                </div>
            </a>
        </div>
        <div class="info-item">
            <a href="{{ route('admin.nav.index', ['top']) }}">
                <div class="title">Верхнее меню</div>
                <div class="info">{{ $top_nav->count() }}</div>
            </a>
        </div>
        <div class="info-item">
            <a href="{{ route('admin.nav.index', ['side']) }}">
                <div class="title">Боковое меню</div>
                <div class="info">{{ $side_nav->count() }}</div>
            </a>
        </div>
    </div>
@endsection