routes/web.php
<?php

Route::get('/', 'PageController@index')->name('home');

Route::resource('cuisines', 'CuisineController')->only(['index', 'show']);
Route::resource('categories', 'CategoryController')->only(['index', 'show']);
Route::resource('dishes', 'DishController')->only(['index', 'show']);


// Cart
Route::group(['prefix' => 'cart',/* 'middleware' => 'auth',*/ 'as' => 'cart.'], function () {
    Route::get('/', 'CartController@index')->name('index');
    Route::get('{dish}/increase', 'CartController@increaseItem')->name('increase');
    Route::get('{dish}/decrease', 'CartController@decreaseItem')->name('decrease');
    Route::get('{dish}/remove', 'CartController@removeItem')->name('remove');
    Route::get('clear', 'CartController@clearCart')->name('clear');
});


// Order
Route::resource('order', 'OrderController')
    ->middleware('auth')
    ->only(['store', 'show']);


// User Panel
Route::group(['prefix' => 'user', 'middleware' => 'auth', 'as' => 'user.'], function () {
    Route::get('/', 'UserController@userIndex')->name('index');
    Route::get('edit', 'UserController@userEdit')->name('edit');
    Route::post('edit/profile', 'UserController@userUpdateProfile')
        ->name('update.profile');
    Route::post('edit/password', 'UserController@userUpdatePassword')
        ->name('update.password');
//    Route::match(['get', 'post'], 'delete', 'UserController@userDestroy')
//        ->name('delete');
});


// Admin Panel
Route::group([
    'prefix' => 'admin',
    'middleware' => ['auth', 'admin'],
    'as' => 'admin.',
], function () {
    Route::get('/', 'AdminController@index')->name('index');

    Route::get('users', 'UserController@admin')->name('users.index');
    Route::get('users/{user}/delete', 'UserController@destroy')
        ->name('users.delete');
    Route::resource('users', 'UserController',
        ['except' => ['index', 'show']]
    );

    Route::get('pages', 'PageController@admin')->name('pages.index');
    Route::get('pages/{page}/delete', 'PageController@destroy')
        ->name('pages.delete');
    Route::resource('pages', 'PageController',
        ['except' => ['index', 'show']]
    );

    Route::get('cuisines', 'CuisineController@admin')
        ->name('cuisines.index');
    Route::get('cuisines/{cuisine}/delete', 'CuisineController@destroy')
        ->name('cuisines.delete');
    Route::resource('cuisines', 'CuisineController',
        ['except' => ['index', 'show']]
    );

    Route::get('categories', 'CategoryController@admin')->name('categories.index');
    Route::get('categories/{category}/delete', 'CategoryController@destroy')
        ->name('categories.delete');
    Route::resource('categories', 'CategoryController',
        ['except' => ['index', 'show']]
    );

    Route::get('dishes', 'DishController@admin')->name('dishes.index');
    Route::get('dishes/{dish}/delete', 'DishController@destroy')
        ->name('dishes.delete');
    Route::resource('dishes', 'DishController',
        ['except' => ['index', 'show']]
    );

    Route::get('cooks', 'CookController@admin')->name('cooks.index');
    Route::get('cooks/{cook}/delete', 'CookController@destroy')
        ->name('cooks.delete');
    Route::resource('cooks', 'CookController',
        ['except' => ['index', 'show']]
    );

    Route::get('orders', 'OrderController@admin')->name('orders.index');
    Route::resource('orders', 'OrderController',
        ['only' => ['edit', 'update']]
    );

    Route::group(['prefix' => '{nav}-nav', 'as' => 'nav.'], function () {
        Route::get('/', 'NavController@admin')->name('index');
        Route::post('/', 'NavController@store')->name('store');
        Route::get('move/{link}/{direction}', 'NavController@move')->name('move');
        Route::get('delete/{link}', 'NavController@destroy')->name('delete');
        Route::get('edit', 'NavController@navEdit')->name('edit');
        Route::post('edit', 'NavController@navUpdate')->name('update');
    });
});


Auth::routes();


// Other page
Route::get('{alias}', 'PageController@show');

app/Http/Controllers/NavController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Page;
use App\TopNav;
use App\SideNav;

class NavController extends Controller
{

    /**
     * Вывод элементов меню в админке
     *
     * @param $nav
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function admin($nav)
    {
        $model    = 'App\\'.ucfirst($nav).'Nav';
        $nav_menu = $model::with('page')->get()->sortBy('weight');

        $pages = Page::all();

        $pages_select = ['-выберите страницу-'];
        foreach ($pages as $page) {
            $pages_select[$page->id] = $page->title;
        }

        $parents_select = ['-нет-'];
        foreach ($nav_menu->where('type', 'submenu') as $link) {
            $parents_select[$link->id] = $link->submenu_title;
        }

        $data = [
            'nav'            => $nav,
            'nav_menu'       => $nav_menu,
            'pages_select'   => $pages_select,
            'parents_select' => $parents_select,
        ];

        return view('admin.nav.index', $data);
    }


    /**
     * @param \Illuminate\Http\Request $request
     * @param                          $nav
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request, $nav)
    {
        if ($request->type == 'url') {
            $rules = [
                'url'       => 'required|url',
                'url_title' => 'required|string',
            ];
        } elseif ($request->type == 'page') {
            $rules = ['page_id' => 'required|regex:/[^0]/u'];
        } elseif ($request->type == 'submenu') {
            $rules = ['submenu_title' => 'required|string'];
        }

        $this->validate($request, $rules);

        $model    = 'App\\'.ucfirst($nav).'Nav';
        $nav_menu = $model::all();
        $count    = $nav_menu->where('parent_id', $request->parent_id)->count();

        $data = [
            'type'          => $request->type,
            'page_id'       => null,
            'url'           => null,
            'url_title'     => null,
            'submenu_title' => null,
            'parent_id'     => $request->parent_id,
            'weight'        => ++$count,
        ];

        if ($request->type == 'url') {
            $data['url']       = $request->url;
            $data['url_title'] = $request->url_title;
        } elseif ($request->type == 'page') {
            $data['page_id'] = $request->page_id;
        } elseif ($request->type == 'submenu') {
            $data['submenu_title'] = $request->submenu_title;
        }

        $model::create($data);

        return redirect()
            ->route('admin.nav.index', compact('nav'))
            ->with("success", "Запись успешно создана!");
    }


    /**
     * Перемещение пункта меню вниз/вверх
     *
     * @param $nav
     * @param $id
     * @param $direction
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function move($nav, $id, $direction)
    {
        $model = 'App\\'.ucfirst($nav).'Nav';

        $link = $model::find($id);

        if ($direction == 'up') {
            $weight          = $link->weight - 1;
        } elseif ($direction == 'down') {
            $weight          = $link->weight + 1;
        }

        $link_exchange   = $model::where('parent_id', $link->parent_id)
                                 ->where('weight', $weight)->first();

        $link_exchange->update(['weight' => $link->weight]);
        $link->update(['weight' => $weight]);

        return redirect()
            ->route('admin.nav.index', compact('nav'))
            ->with("success", "Запись успешно перемещена!");
    }


    /**
     * Удаление пункта меню
     *
     * @param $nav
     * @param $id
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($nav, $id)
    {
        $model = 'App\\'.ucfirst($nav).'Nav';

        $link = $model::find($id);

        if ($this->deleteMenuItems($model, $link)) {
            $this->shiftMenuItems($model, $link);

            return redirect()
                ->route('admin.nav.index', compact('nav'))
                ->with("success", "Запись успешно удалена!");
        }
    }


    /**
     * Рекурсивное удаление пункта меню и всех его подпунктоа
     *
     * @param $model
     * @param $item
     *
     * @return bool
     */
    private function deleteMenuItems($model, $item)
    {
        $children = $model::where('parent_id', $item->id)->get();

        if ($children->count() > 0) {
            foreach ($children as $link) {
                $this->deleteMenuItems($model, $link);

                $link->delete();
            }
        }

        $item->delete();

        return true;
    }


    /**
     * Смещение номера пунктов меню после удаленного
     *
     * @param $model
     * @param $item
     */
    private function shiftMenuItems($model, $item)
    {
        $items = $model::where('parent_id', $item->parent_id)
                       ->where('weight', '>', $item->weight)
                       ->get();

        foreach ($items as $item) {
            $weight = $item->weight - 1;
            $item->update(['weight' => $weight]);
        }

        return;
    }
}

resources/views/admin/nav/edit.blade.php
@extends('layouts.admin')

@section('pageDescription', '')
@section('pageTitle', 'Админпанель | ')

@section('breadcrumb', Breadcrumbs::render(Route::currentRouteName(), $nav))

@section('content')
    {!! Form::open(['action'=>['AdminController@navUpdate', $nav]]) !!}

    @foreach($nav_menu as $link)
        <div class="group">
            {!! Form::selectRange("links[{$link->id}][weight]", 1, $nav_menu->count(), $link->weight, ['class'=>'small']) !!}
            {!! Form::select("links[{$link->id}][page_id]", $pages_select, $link->page_id) !!}
            {!! Form::select("links[{$link->id}][parent_id]", $parents_select, $link->parent_id) !!}
        </div>

        <div class="group">
            @if($errors->has("links.{$link->id}.weight"))
                <p class="error">{{ $errors->first("links.{$link->id}.weight") }}</p>
            @endif

            @if($errors->has("links.{$link->id}.page_id"))
                <p class="error">{{ $errors->first("links.{$link->id}.page_id") }}</p>
            @endif

            @if($errors->has("links.{$link->id}.parent_id"))
                <p class="error">{{ $errors->first("links.{$link->id}.parent_id") }}</p>
            @endif
        </div>
    @endforeach

    <div class="group">
        {!! Form::submit('Сохранить изменения', ['class' => 'submit']) !!}
    </div>
    {!! Form::close() !!}
@endsection

resources/views/admin/nav/index.blade.php
@extends('layouts.admin')

@section('pageDescription', '')
@section('pageTitle', 'Админпанель | ')

@section('breadcrumb', Breadcrumbs::render(Route::currentRouteName(), $nav))

@section('new-item')
    <a href="#" class="add add-item-btn">Новый пункт</a>
@endsection

@section('content')
    @if($errors->has('url_title'))
        <p class="error">{{ $errors->first('url_title') }}</p>
    @endif
    @if($errors->has('url'))
        <p class="error">{{ $errors->first('url') }}</p>
    @endif
    @if($errors->has('page_id'))
        <p class="error">{{ $errors->first('page_id') }}</p>
    @endif
    @if($errors->has('submenu_title'))
        <p class="error">{{ $errors->first('submenu_title') }}</p>
    @endif
    @if($errors->has('parent_id'))
        <p class="error">{{ $errors->first('parent_id') }}</p>
    @endif

    {!! view('admin.nav.menu_list', ['nav' => $nav, 'nav_menu' => $nav_menu,'current' => $nav_menu->where('parent_id', 0)]) !!}

    <div class="overlay">
        <div class="add-nav-item">
            <button class="close-btn">
                <i class="fa fa-times" aria-hidden="true"></i>
            </button>

            <div class="buttons">
                <button class="active">
                    <label for="url">Ссылка</label>
                </button>
                <button>
                    <label for="page">Страница</label>
                </button>
                <button>
                    <label for="submenu">Подменю</label>
                </button>
            </div>

            {!! Form::open(['route'=>['admin.nav.store', $nav]]) !!}
            {!! Form::radio('type', 'url', true, ['id'=>'url', 'hidden']) !!}
            {!! Form::radio('type', 'page', null, ['id'=>'page', 'hidden']) !!}
            {!! Form::radio('type', 'submenu', null, ['id'=>'submenu', 'hidden']) !!}
            <div class="group url active">
                {!! Form::label('Имя пункта') !!}
                {!! Form::text('url_title', null, ['placeholder'=>'имя пункта']) !!}
            </div>
            <div class="group url active">
                {!! Form::label('Ссылка') !!}
                {!! Form::text('url', 'http://', ['placeholder'=>'ссылка (http://...)']) !!}
            </div>
            <div class="group page">
                {!! Form::label('Страница') !!}
                {!! Form::select('page_id', $pages_select, null) !!}
            </div>
            <div class="group submenu">
                {!! Form::label('Подменю') !!}
                {!! Form::text('submenu_title', null, ['placeholder'=>'имя пункта']) !!}
            </div>
            <div class="group">
                {!! Form::label('Родительский пункт') !!}
                {!! Form::select('parent_id', $parents_select, null) !!}
            </div>
            <div class="group">
                {!! Form::submit('Добавить пункт меню', ['class' => 'submit']) !!}
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/nav/menu_list.blade.php
<ul class="menu-list">
    @foreach($current as $link)
        <li>
            <div class="info">
                @if($link->type == 'url')
                    <span>Ссылка: </span>{{ $link->url_title }} (<i>{{ link_to($link->url) }})</i>
                @elseif($link->type == 'page')
                    <span>Страница: </span>{{ $link->page->title }}
                @elseif($link->type == 'submenu')
                    <span>Подменю: </span>{{ $link->submenu_title }}
                @endif

                <div class="buttons">
                    <a href="">
                        <i class="fa fa-pencil" aria-hidden="true"></i>
                    </a>
                    <a href="{{ route('admin.nav.delete', [$nav, 'id' => $link->id]) }}" class="delete-item-btn">
                        <i class="fa fa-trash" aria-hidden="true"></i>
                    </a>
                    <div class="move">
                        @if($link->weight > 1)
                            <a href="{{ route('admin.nav.move', [$nav, 'id' => $link->id, 'direction' => 'up']) }}">
                                <i class="fa fa-arrow-up" aria-hidden="true"></i>
                            </a>
                        @else
                            <a href="" class="not-active">
                                <i class="fa fa-arrow-up" aria-hidden="true"></i>
                            </a>
                        @endif

                        @if($link->weight < $current->count())
                            <a href="{{ route('admin.nav.move', [$nav, 'id' => $link->id, 'direction' => 'down']) }}">
                                <i class="fa fa-arrow-down" aria-hidden="true"></i>
                            </a>
                        @else
                            <a href="" class="not-active"><i class="fa fa-arrow-down" aria-hidden="true"></i></a>
                        @endif
                    </div>
                </div>
            </div>

            @if($link->type == 'submenu')
                {!! view('admin.nav.menu_list', ['nav' => $nav, 'nav_menu' => $nav_menu,'current' => $nav_menu->where('parent_id', $link->id)]) !!}
            @endif
        </li>
    @endforeach
</ul>